# numpy test code

In [12]:
import numpy as np



## 벡터 내적. 매트릭스 곱. DOT 

In [13]:
a=np.random.randint(0,5, 3) # 0~4 , count 3
b=np.random.randint(1,6, 3) # 1~5 , count 3
print(a, b, np.dot(a,b) ) # vector inner product

[4 2 1] [2 1 5] 15


## Array 생성

In [176]:
print( np.zeros(5) ) 
print( np.zeros((2,3))) # tuple input
print( np.ones(5))
print( np.empty((2,3)))  # tuple input 
print( np.array( [1,2,3 ])) # list to array
print( np.array( [ [1,2], [3,4]])) # list to array
print( np.array( [9]*2*5).reshape( 2, 5 ) )

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1 2 3]
[[1 2]
 [3 4]]
[[9 9 9 9 9]
 [9 9 9 9 9]]


In [15]:
print ( np.random.randn(2,3) )  # (-2~2) 2x3
print ( np.random.randint(1,10,4)) # (1~9) 4
print ( np.random.randint(1,10,(2,3))) # (1~9) 2x3
print( np.random.rand(3)) # (0~1) 3
print( np.random.random(3)) # "
print( np.random.rand(2,3)) # (0~1) 2x3

[[-1.60099269  0.61807954  1.13623565]
 [ 1.02902152  0.23009556  0.07578964]]
[5 4 6 5]
[[5 3 6]
 [9 8 6]]
[0.72813394 0.53195946 0.93256288]
[0.62988388 0.22672758 0.93457449]
[[0.64341976 0.83527204 0.49004299]
 [0.3910581  0.58398958 0.23411563]]


In [16]:
# type
x = np.array([-1.6, 1.2, 2.1])
print(x, type(x))
x = x.astype(np.int)
print(x, type(x))

[-1.6  1.2  2.1] <class 'numpy.ndarray'>
[-1  1  2] <class 'numpy.ndarray'>


* 리스트를 이용한 numpy array 생성

In [17]:
a=[["abc" for i in range(3)] for i in range(2) ]
print (a, ' type=', type(a) )
b=np.asarray(a)
print (b, 'type=', type(b))

[['abc', 'abc', 'abc'], ['abc', 'abc', 'abc']]  type= <class 'list'>
[['abc' 'abc' 'abc']
 ['abc' 'abc' 'abc']] type= <class 'numpy.ndarray'>


## 행렬 붙이기 (matrix concat)

###   1.row bind

In [18]:
a=np.random.randint(1,10,4)
mat=np.ones((3,4))
print('mat=\n',mat)
print('a=\n',a)
rowbind = np.r_[mat, [a]]   ## warn! : a shape
print('rowbind=\n', rowbind)
rowbind = np.r_[[a], mat]
print('rowbind=\n', rowbind)

mat=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
a=
 [7 2 3 8]
rowbind=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [7. 2. 3. 8.]]
rowbind=
 [[7. 2. 3. 8.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [195]:
a=np.zeros((2,4))
rowbind = np.r_[mat, a]
print('rowbind=\n', rowbind)

rowbind=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [197]:
## vstack. row add
a=np.array([[2,3], [4,5], [6,7]])
print(a)
b=np.vstack( (a, np.zeros((1,2)) )) # 차원을 맞춰야 함 
print(b)

[[2 3]
 [4 5]
 [6 7]]
[[2. 3.]
 [4. 5.]
 [6. 7.]
 [0. 0.]]


### 한 줄씩 추가하기

In [9]:
# empty array and append row
a = np.empty((0,3))
b = np.random.randint(1,5,3)
a = np.r_[a,[b]]
print(a)
b = np.random.randint(1,5,3)
a = np.r_[a,[b]]
print(a)


[[3. 4. 3.]]
[[3. 4. 3.]
 [3. 4. 4.]]


In [ ]:
#### list를 사용하여 append로 추가하고 나중에 numpy로 형변환 하는 방식도 있다.

### 2.column bind

In [10]:
a=np.random.randint(1,10,3)
mat=np.ones((3,4))
print('mat=\n',mat)
print('a=\n',a)
colbind = np.c_[mat, a]
print('colbind=\n', colbind)
colbind = np.c_[a, mat]
print('colbind=\n', colbind)

mat=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
a=
 [9 9 7]
colbind=
 [[1. 1. 1. 1. 9.]
 [1. 1. 1. 1. 9.]
 [1. 1. 1. 1. 7.]]
colbind=
 [[9. 1. 1. 1. 1.]
 [9. 1. 1. 1. 1.]
 [7. 1. 1. 1. 1.]]


In [20]:
a=np.zeros((3,2))
colbind = np.c_[mat, a]
print('colbind=\n', colbind)

colbind=
 [[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [172]:
## hstack. column add
a=np.array([[2,3], [4,5], [6,7]])
print(a)
print(np.zeros((3,1)))
b=np.hstack( (a, np.zeros((3,1)) )) # 차원을 맞춰야 함 
print(b)


[[2 3]
 [4 5]
 [6 7]]
[[0.]
 [0.]
 [0.]]
[[2. 3. 0.]
 [4. 5. 0.]
 [6. 7. 0.]]


### Append

In [184]:
# 컬럼이나 열 추가
a=np.array([[1,2,3],[4,5,6]])
b=np.append(a, [[7,8,9]])
print(b)
b=np.append(a, [[7,8,9]], axis=0) # rows append
print(b)
b=np.append(a, [[7,8],[9,10]], axis=1) #  columns append
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


### Insert

In [194]:
# insert
print(a)
b=np.insert(a, 1, [1,1,1], axis=0) # insert row
print(b)
b=np.insert(a, 1, 99, axis=0) # insert row, fill 99
print(b)
b=np.insert(a, 1, 0, axis=1) # insert col. fill 0
print(b)
b=np.insert(a, -1, 8, axis=1) # insert col. fill 8
print(b)
b=np.insert(a, a.shape[1], 8, axis=1) # insert col. fill 8
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [1 1 1]
 [4 5 6]]
[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]]
[[1 0 2 3]
 [4 0 5 6]]
[[1 2 8 3]
 [4 5 8 6]]
[[1 2 3 8]
 [4 5 6 8]]


## 집합 연산 

In [26]:
ar1=np.array([1,2,4])
ar2=np.array([2,3,5])
print( 'union=', np.union1d(ar1, ar2))
print('insersect=', np.intersect1d(ar1, ar2))
print('setdiff=', np.setdiff1d(ar1, ar2)) # ar1-ar2
print('setxor1d=', np.setxor1d(ar1, ar2)) # union - intersect

union= [1 2 3 4 5]
insersect= [2]
setdiff= [1 4]
setxor1d= [1 3 4 5]


## 정렬 (Sort)

In [98]:
a=np.array([4,8,2,6])
print ('a=',a, a.shape, a.ndim)
print ( 'reverse =', a[::-1])   # reverse order
a.sort()  # modified a
print('sorted a=', a)   # increase (ascendant)
a=np.array( [[3,2,4], [4,1,2], [2,2,1]] )
print( 'sort np.sort=\n', np.sort(a)) # a is not changed.  column sort
print('sort by row=\n', np.sort(a, axis=0)) # row sort
print('sort flatten=\n', np.sort(a, axis=None)) # flatten

# sort by column with keeping record.
print('a=\n',a, a.dtype)
a=a[a[:,1].argsort()]    # sort by column index 1
print('sort by column 2 = \n', a)
a=a[a[:,0].argsort(kind='mergesort')]    # sort by column index 0
print('sort by column 1 = \n', a)


a= [4 8 2 6] (4,) 1
reverse = [6 2 8 4]
sorted a= [2 4 6 8]
sort np.sort=
 [[2 3 4]
 [1 2 4]
 [1 2 2]]
sort by row=
 [[2 1 1]
 [3 2 2]
 [4 2 4]]
sort flatten=
 [1 1 2 2 2 2 3 4 4]
a=
 [[3 2 4]
 [4 1 2]
 [2 2 1]] int64
sort by column 2 = 
 [[4 1 2]
 [3 2 4]
 [2 2 1]]
sort by column 1 = 
 [[2 2 1]
 [3 2 4]
 [4 1 2]]


In [75]:

# sort by multiple key. 
b=np.array( [(3,4,4),(2,4,5),(1,1,1)], dtype=[('f1', int), ('f2',int), ('f3', int)])
print(b)
print ( np.sort(b, order=['f2','f1']))

[(3, 4, 4) (2, 4, 5) (1, 1, 1)]
[(1, 1, 1) (2, 4, 5) (3, 4, 4)]


In [77]:
# descendent sort
a=np.array([4,8,2,6])
print('sort desc=', np.sort(a)[::-1])  # sort asc and reverse.


sort desc= [8 6 4 2]


### 인덱스  (index)

In [87]:
# 최대값 위치의 인덱스 얻기
a=np.array([4,8,1,2,9,4])
print( 'maxvalue index=', np.argmax(a), ' max value=', a[np.argmax(a)], np.max(a))
# 2D
a=np.array( [[3,2,4], [4,1,2], [2,3,4]] )
print(a)
print('maxvalue index(ax=0)=', np.argmax(a, axis=0)) # compare by row. y-axis.
print('maxvalue index(ax=1)=', np.argmax(a, axis=1)) # compare by column. x-axis.

maxvalue index= 4  max value= 9 9
[[3 2 4]
 [4 1 2]
 [2 3 4]]
maxvalue index(ax=0)= [1 2 0]
maxvalue index(ax=1)= [2 0 2]


In [89]:
# 순위. 오름차순 정렬의 인덱스 번호. (sort를 하는데, 인덱스 순서만 구함)
print( 'sort arg (ax=0)\n', np.argsort(a, axis=0))

sort arg (ax=0)
 [[2 1 1]
 [0 0 0]
 [1 2 2]]


In [96]:
b=np.array([180,175,160,170])
print( np.argsort(b)) # b를 오름차순 정렬한 데이터의 원래 인덱스 번호 순서 
print( np.argsort(-b)) # 내림차순
print( np.sort(b)[::-1][:3]) # big top 3 ; 역순정렬후 3개만 가져옴.

[2 3 1 0]
[0 1 3 2]
[180 175 170]


## 필터 / 추출 Filter

In [107]:
a=np.array([1,2,3,6,7,9])
print( a>4 )  # bool. mask
print ( np.array(a>4, dtype=int)) # as integer
print( 'over 4=', a[a>4], ' over 4 cnt=', len(a[a>4]) ) # filter condition
print('index 2~4=', a[2:5],  'last one=', a[-1])  # index start, end+1

[False False False  True  True  True]
[0 0 0 1 1 1]
over 4= [6 7 9]  over 4 cnt= 3
index 2~4= [3 6 7] last one= 9


In [117]:
# 중복 제거
a=np.array([1,2,6,0,8,2,0,6])
print ( 'remove dupl=', np.unique(a))
# 0 제거
print( ' non zero=', np.nonzero(a))
print(a[np.nonzero(a)])

remove dupl= [0 1 2 6 8]
 non zero= (array([0, 1, 2, 4, 5, 7]),)
[1 2 6 8 2 6]


In [120]:
# 검색 Search
a=np.array([1,4,2,3,6,7,3])
print( np.where(a==3) ) # find 3 value . and get the index num.
print( 'how many 3?=', np.where(a==3)[0].size)
print('first 3 index=', np.where(a==3)[0][0])

(array([3, 6]),)
how many 3?= 2
first 3 index= 3


<pre>
# where in Matrix.

itemindex = np.where(array==item)     ; row, column 값들이 리턴. (2차원, 튜플)
array[ itemindex[0][0]] [ itemindex[1][0] ]
array[ itemindex[0][1]] [ itemindex[1][1] ]
</pre>


### Numpy Save & Load

In [153]:
a=np.random.randn(3,4)
b=np.random.randn(3,4)
print(a)
print(b)

## 배열 한 개 저장/로딩 (확장자 npy)
np.save('tmpfile001.npy', a)  # .npy (default extension. auto added)
d=np.load('tmpfile001.npy')  # need file extension.
print(d)

## 배열 복수개 저장/로딩 (확장자 npz)
np.savez('tmpfile001.npz', a=a,b=b) # 배열에 이름을 지정 필요.
c = np.load('tmpfile001.npz')
print(c)
print(c['a'])
print(c['b'])
c.close() # close file.

## 압축
np.savez_compressed('tmpfile002', a=a, b=b)
c = np.load('tmpfile002.npz')
print(c)
print(c['a'])
print(c['b'])
c.close() # close file.


[[-1.47377096 -0.4867424   0.65394763  0.79714288]
 [ 0.80682589 -0.06776694  1.22872369  0.06181822]
 [-0.57806519 -1.52542053 -1.05119565  0.62924111]]
[[-0.28502782  0.21832423  1.15674393  0.43357922]
 [-1.00176783  0.82191963  0.29277696 -0.53469207]
 [-0.208886    0.94037607 -0.75343871 -0.1703181 ]]
[[-1.47377096 -0.4867424   0.65394763  0.79714288]
 [ 0.80682589 -0.06776694  1.22872369  0.06181822]
 [-0.57806519 -1.52542053 -1.05119565  0.62924111]]
[[-1.47377096 -0.4867424   0.65394763  0.79714288]
 [ 0.80682589 -0.06776694  1.22872369  0.06181822]
 [-0.57806519 -1.52542053 -1.05119565  0.62924111]]
[[-0.28502782  0.21832423  1.15674393  0.43357922]
 [-1.00176783  0.82191963  0.29277696 -0.53469207]
 [-0.208886    0.94037607 -0.75343871 -0.1703181 ]]
[[-1.47377096 -0.4867424   0.65394763  0.79714288]
 [ 0.80682589 -0.06776694  1.22872369  0.06181822]
 [-0.57806519 -1.52542053 -1.05119565  0.62924111]]
[[-0.28502782  0.21832423  1.15674393  0.43357922]
 [-1.00176783  0.82191963

In [156]:
## Text로 저장
a=np.random.randn(3,4)
print(a)
np.savetxt('tmpfile003.txt', a, header='--start--', footer='-end-')

with open('tmpfile003.txt', 'rt') as f :
    print(f.read())

[[ 0.65251165 -0.69495371 -1.63105204  0.35989324]
 [ 1.30292472 -0.7421428  -0.92000098 -0.30618059]
 [-0.17755657 -0.27355098 -0.02635187 -1.42221376]]
# --start--
6.525116538344829520e-01 -6.949537083354661027e-01 -1.631052036828422258e+00 3.598932360947073583e-01
1.302924724015655400e+00 -7.421427977504930773e-01 -9.200009808827286362e-01 -3.061805856432851525e-01
-1.775565719541135901e-01 -2.735509788014691690e-01 -2.635186579102788071e-02 -1.422213755338526786e+00
# -end-



In [157]:
loaddata = np.loadtxt('tmpfile003.txt')
print(loaddata)

[[ 0.65251165 -0.69495371 -1.63105204  0.35989324]
 [ 1.30292472 -0.7421428  -0.92000098 -0.30618059]
 [-0.17755657 -0.27355098 -0.02635187 -1.42221376]]


## 행렬 Matrix

### Reshape

In [162]:
## reshape (row x col)
a=np.array([1,2,3,4,5,6])
print ( a.reshape(-1,3)) # ? x 3
print( a.reshape(3,2)) # 3 x 2

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [164]:
# reshape ; 컬럼순서로 데이터를 채울때는 order F
b=a.reshape(3,2, order='F')
print (b)

[[1 4]
 [2 5]
 [3 6]]


In [202]:
## Flatten 1D
b=np.array( [[1,2,3], [4,5,6]])
print(b.flatten())  # make 1D
print ( np.squeeze(b) ) # remove single dimensionl entries
b=np.array([[[1]],[[2]]])
print(b)
print(b.flatten())  # make 1D
print ( np.squeeze(b) ) # remove single dimensionl entries

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1]]

 [[2]]]
[1 2]
[1 2]


In [204]:
# reorder
b=np.array( [[1,2,3], [4,5,6]])
print(b)
print( np.fliplr(b) )
print( np.flipud(b) )
print( np.roll(b, 1, axis=1))

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[3 1 2]
 [6 4 5]]
