# numpy test code

In [1]:
import numpy as np



## 벡터 내적. 매트릭스 곱. DOT 

In [2]:
a=np.random.randint(0,5, 3) # 0~4 , count 3
b=np.random.randint(1,6, 3) # 1~5 , count 3
print(a, b, np.dot(a,b) ) # vector inner product

[3 1 4] [4 1 4] 29


## Array 생성

In [3]:
print( np.zeros(5) ) 
print( np.zeros((2,3))) # tuple input
print( np.ones(5))
print( np.empty((2,3)))  # tuple input 
print( np.array( [1,2,3 ])) # list to array
print( np.array( [ [1,2], [3,4]])) # list to array
print( np.array( [9]*2*5).reshape( 2, 5 ) )

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1 2 3]
[[1 2]
 [3 4]]
[[9 9 9 9 9]
 [9 9 9 9 9]]


In [4]:
print ( np.random.randn(2,3) )  # (-2~2) 2x3
print ( np.random.randint(1,10,4)) # (1~9) 4
print ( np.random.randint(1,10,(2,3))) # (1~9) 2x3
print( np.random.rand(3)) # (0~1) 3
print( np.random.random(3)) # "
print( np.random.rand(2,3)) # (0~1) 2x3

[[-1.24977829 -0.67500634  0.56732312]
 [ 1.16595907 -0.250152    0.1974678 ]]
[6 5 9 9]
[[8 4 5]
 [1 5 7]]
[0.50528455 0.11636728 0.79242234]
[0.45164485 0.22054391 0.69378478]
[[0.96448321 0.50241084 0.06380248]
 [0.61599347 0.93752352 0.93597434]]


In [5]:
# type
x = np.array([-1.6, 1.2, 2.1])
print(x, type(x))
x = x.astype(np.int)
print(x, type(x))

[-1.6  1.2  2.1] <class 'numpy.ndarray'>
[-1  1  2] <class 'numpy.ndarray'>


* 리스트를 이용한 numpy array 생성

In [6]:
a=[["abc" for i in range(3)] for i in range(2) ]
print (a, ' type=', type(a) )
b=np.asarray(a)
print (b, 'type=', type(b))

[['abc', 'abc', 'abc'], ['abc', 'abc', 'abc']]  type= <class 'list'>
[['abc' 'abc' 'abc']
 ['abc' 'abc' 'abc']] type= <class 'numpy.ndarray'>


## 행렬 붙이기 (matrix concat)

###   1.row bind

In [7]:
a=np.random.randint(1,10,4)
mat=np.ones((3,4))
print('mat=\n',mat)
print('a=\n',a)
rowbind = np.r_[mat, [a]]   ## warn! : a shape
print('rowbind=\n', rowbind)
rowbind = np.r_[[a], mat]
print('rowbind=\n', rowbind)

mat=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
a=
 [7 4 7 8]
rowbind=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [7. 4. 7. 8.]]
rowbind=
 [[7. 4. 7. 8.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
a=np.zeros((2,4))
rowbind = np.r_[mat, a]
print('rowbind=\n', rowbind)

rowbind=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
## vstack. row add
a=np.array([[2,3], [4,5], [6,7]])
print(a)
b=np.vstack( (a, np.zeros((1,2)) )) # 차원을 맞춰야 함 
print(b)

[[2 3]
 [4 5]
 [6 7]]
[[2. 3.]
 [4. 5.]
 [6. 7.]
 [0. 0.]]


### 한 줄씩 추가하기

In [10]:
# empty array and append row
a = np.empty((0,3))
b = np.random.randint(1,5,3)
a = np.r_[a,[b]]
print(a)
b = np.random.randint(1,5,3)
a = np.r_[a,[b]]
print(a)


[[2. 1. 1.]]
[[2. 1. 1.]
 [4. 1. 3.]]


In [11]:
#### list를 사용하여 append로 추가하고 나중에 numpy로 형변환 하는 방식도 있다.

### 2.column bind

In [12]:
a=np.random.randint(1,10,3)
mat=np.ones((3,4))
print('mat=\n',mat)
print('a=\n',a)
colbind = np.c_[mat, a]
print('colbind=\n', colbind)
colbind = np.c_[a, mat]
print('colbind=\n', colbind)

mat=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
a=
 [3 1 1]
colbind=
 [[1. 1. 1. 1. 3.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
colbind=
 [[3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
a=np.zeros((3,2))
colbind = np.c_[mat, a]
print('colbind=\n', colbind)

colbind=
 [[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [14]:
## hstack. column add
a=np.array([[2,3], [4,5], [6,7]])
print(a)
print(np.zeros((3,1)))
b=np.hstack( (a, np.zeros((3,1)) )) # 차원을 맞춰야 함 
print(b)


[[2 3]
 [4 5]
 [6 7]]
[[0.]
 [0.]
 [0.]]
[[2. 3. 0.]
 [4. 5. 0.]
 [6. 7. 0.]]


### Append

In [15]:
# 컬럼이나 열 추가
a=np.array([[1,2,3],[4,5,6]])
b=np.append(a, [[7,8,9]])
print(b)
b=np.append(a, [[7,8,9]], axis=0) # rows append
print(b)
b=np.append(a, [[7,8],[9,10]], axis=1) #  columns append
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


### Insert

In [16]:
# insert
print(a)
b=np.insert(a, 1, [1,1,1], axis=0) # insert row
print(b)
b=np.insert(a, 1, 99, axis=0) # insert row, fill 99
print(b)
b=np.insert(a, 1, 0, axis=1) # insert col. fill 0
print(b)
b=np.insert(a, -1, 8, axis=1) # insert col. fill 8
print(b)
b=np.insert(a, a.shape[1], 8, axis=1) # insert col. fill 8
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [1 1 1]
 [4 5 6]]
[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]]
[[1 0 2 3]
 [4 0 5 6]]
[[1 2 8 3]
 [4 5 8 6]]
[[1 2 3 8]
 [4 5 6 8]]


## 집합 연산 

In [17]:
ar1=np.array([1,2,4])
ar2=np.array([2,3,5])
print( 'union=', np.union1d(ar1, ar2))
print('insersect=', np.intersect1d(ar1, ar2))
print('setdiff=', np.setdiff1d(ar1, ar2)) # ar1-ar2
print('setxor1d=', np.setxor1d(ar1, ar2)) # union - intersect

union= [1 2 3 4 5]
insersect= [2]
setdiff= [1 4]
setxor1d= [1 3 4 5]


## 정렬 (Sort)

In [18]:
a=np.array([4,8,2,6])
print ('a=',a, a.shape, a.ndim)
print ( 'reverse =', a[::-1])   # reverse order
a.sort()  # modified a
print('sorted a=', a)   # increase (ascendant)
a=np.array( [[3,2,4], [4,1,2], [2,2,1]] )
print( 'sort np.sort=\n', np.sort(a)) # a is not changed.  column sort
print('sort by row=\n', np.sort(a, axis=0)) # row sort
print('sort flatten=\n', np.sort(a, axis=None)) # flatten

# sort by column with keeping record.
print('a=\n',a, a.dtype)
a=a[a[:,1].argsort()]    # sort by column index 1
print('sort by column 2 = \n', a)
a=a[a[:,0].argsort(kind='mergesort')]    # sort by column index 0
print('sort by column 1 = \n', a)


a= [4 8 2 6] (4,) 1
reverse = [6 2 8 4]
sorted a= [2 4 6 8]
sort np.sort=
 [[2 3 4]
 [1 2 4]
 [1 2 2]]
sort by row=
 [[2 1 1]
 [3 2 2]
 [4 2 4]]
sort flatten=
 [1 1 2 2 2 2 3 4 4]
a=
 [[3 2 4]
 [4 1 2]
 [2 2 1]] int64
sort by column 2 = 
 [[4 1 2]
 [3 2 4]
 [2 2 1]]
sort by column 1 = 
 [[2 2 1]
 [3 2 4]
 [4 1 2]]


In [19]:

# sort by multiple key. 
b=np.array( [(3,4,4),(2,4,5),(1,1,1)], dtype=[('f1', int), ('f2',int), ('f3', int)])
print(b)
print ( np.sort(b, order=['f2','f1']))

[(3, 4, 4) (2, 4, 5) (1, 1, 1)]
[(1, 1, 1) (2, 4, 5) (3, 4, 4)]


In [20]:
# descendent sort
a=np.array([4,8,2,6])
print('sort desc=', np.sort(a)[::-1])  # sort asc and reverse.


sort desc= [8 6 4 2]


### 인덱스  (index)

In [21]:
# 최대값 위치의 인덱스 얻기
a=np.array([4,8,1,2,9,4])
print( 'maxvalue index=', np.argmax(a), ' max value=', a[np.argmax(a)], np.max(a))
# 2D
a=np.array( [[3,2,4], [4,1,2], [2,3,4]] )
print(a)
print('maxvalue index(ax=0)=', np.argmax(a, axis=0)) # compare by row. y-axis.
print('maxvalue index(ax=1)=', np.argmax(a, axis=1)) # compare by column. x-axis.

maxvalue index= 4  max value= 9 9
[[3 2 4]
 [4 1 2]
 [2 3 4]]
maxvalue index(ax=0)= [1 2 0]
maxvalue index(ax=1)= [2 0 2]


In [22]:
# 순위. 오름차순 정렬의 인덱스 번호. (sort를 하는데, 인덱스 순서만 구함)
print( 'sort arg (ax=0)\n', np.argsort(a, axis=0))

sort arg (ax=0)
 [[2 1 1]
 [0 0 0]
 [1 2 2]]


In [23]:
b=np.array([180,175,160,170])
print( np.argsort(b)) # b를 오름차순 정렬한 데이터의 원래 인덱스 번호 순서 
print( np.argsort(-b)) # 내림차순
print( np.sort(b)[::-1][:3]) # big top 3 ; 역순정렬후 3개만 가져옴.

[2 3 1 0]
[0 1 3 2]
[180 175 170]


## 필터 / 추출 Filter

In [24]:
a=np.array([1,2,3,6,7,9])
print( a>4 )  # bool. mask
print ( np.array(a>4, dtype=int)) # as integer
print( 'over 4=', a[a>4], ' over 4 cnt=', len(a[a>4]) ) # filter condition
print('index 2~4=', a[2:5],  'last one=', a[-1])  # index start, end+1

[False False False  True  True  True]
[0 0 0 1 1 1]
over 4= [6 7 9]  over 4 cnt= 3
index 2~4= [3 6 7] last one= 9


In [25]:
# 중복 제거
a=np.array([1,2,6,0,8,2,0,6])
print ( 'remove dupl=', np.unique(a))
# 0 제거
print( ' non zero=', np.nonzero(a))
print(a[np.nonzero(a)])

remove dupl= [0 1 2 6 8]
 non zero= (array([0, 1, 2, 4, 5, 7]),)
[1 2 6 8 2 6]


In [26]:
# 검색 Search
a=np.array([1,4,2,3,6,7,3])
print( np.where(a==3) ) # find 3 value . and get the index num.
print( 'how many 3?=', np.where(a==3)[0].size)
print('first 3 index=', np.where(a==3)[0][0])

(array([3, 6]),)
how many 3?= 2
first 3 index= 3


<pre>
# where in Matrix.

itemindex = np.where(array==item)     ; row, column 값들이 리턴. (2차원, 튜플)
array[ itemindex[0][0]] [ itemindex[1][0] ]
array[ itemindex[0][1]] [ itemindex[1][1] ]
</pre>


### Numpy Save & Load

In [27]:
a=np.random.randn(3,4)
b=np.random.randn(3,4)
print(a)
print(b)

## 배열 한 개 저장/로딩 (확장자 npy)
np.save('tmpfile001.npy', a)  # .npy (default extension. auto added)
d=np.load('tmpfile001.npy')  # need file extension.
print(d)

## 배열 복수개 저장/로딩 (확장자 npz)
np.savez('tmpfile001.npz', a=a,b=b) # 배열에 이름을 지정 필요.
c = np.load('tmpfile001.npz')
print(c)
print(c['a'])
print(c['b'])
c.close() # close file.

## 압축
np.savez_compressed('tmpfile002', a=a, b=b)
c = np.load('tmpfile002.npz')
print(c)
print(c['a'])
print(c['b'])
c.close() # close file.


[[-0.2746646  -0.97892704  1.32221441  0.16607678]
 [-1.19822787  0.85798036  1.2278446   0.09228706]
 [ 2.43503874 -1.2570709   0.98594485  1.12458703]]
[[-1.20564842 -1.57481369  0.14462292 -0.01429168]
 [-0.02644696  0.11432339  0.83380484 -3.17339834]
 [-0.90862153 -0.67743711 -1.09119505 -0.51372899]]
[[-0.2746646  -0.97892704  1.32221441  0.16607678]
 [-1.19822787  0.85798036  1.2278446   0.09228706]
 [ 2.43503874 -1.2570709   0.98594485  1.12458703]]
[[-0.2746646  -0.97892704  1.32221441  0.16607678]
 [-1.19822787  0.85798036  1.2278446   0.09228706]
 [ 2.43503874 -1.2570709   0.98594485  1.12458703]]
[[-1.20564842 -1.57481369  0.14462292 -0.01429168]
 [-0.02644696  0.11432339  0.83380484 -3.17339834]
 [-0.90862153 -0.67743711 -1.09119505 -0.51372899]]
[[-0.2746646  -0.97892704  1.32221441  0.16607678]
 [-1.19822787  0.85798036  1.2278446   0.09228706]
 [ 2.43503874 -1.2570709   0.98594485  1.12458703]]
[[-1.20564842 -1.57481369  0.14462292 -0.01429168]
 [-0.02644696  0.11432339

In [28]:
## Text로 저장
a=np.random.randn(3,4)
print(a)
np.savetxt('tmpfile003.txt', a, header='--start--', footer='-end-')

with open('tmpfile003.txt', 'rt') as f :
    print(f.read())

[[ 0.07819498 -0.71882616 -1.02808705 -1.02902502]
 [-1.05972817 -1.98388804  0.74635533 -0.8361366 ]
 [ 1.64284086  0.41005991 -0.6543423   0.37279761]]
# --start--
7.819497739131224534e-02 -7.188261647557899758e-01 -1.028087052737584495e+00 -1.029025022096556219e+00
-1.059728167593185777e+00 -1.983888043826486092e+00 7.463553299749940972e-01 -8.361366033343421433e-01
1.642840855143101075e+00 4.100599128219770129e-01 -6.543423004878126115e-01 3.727976081123280938e-01
# -end-



In [29]:
loaddata = np.loadtxt('tmpfile003.txt')
print(loaddata)

[[ 0.07819498 -0.71882616 -1.02808705 -1.02902502]
 [-1.05972817 -1.98388804  0.74635533 -0.8361366 ]
 [ 1.64284086  0.41005991 -0.6543423   0.37279761]]


## 행렬 Matrix

### Reshape

In [30]:
## reshape (row x col)
a=np.array([1,2,3,4,5,6])
print ( a.reshape(-1,3)) # ? x 3
print( a.reshape(3,2)) # 3 x 2

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [31]:
# reshape ; 컬럼순서로 데이터를 채울때는 order F
b=a.reshape(3,2, order='F')
print (b)

[[1 4]
 [2 5]
 [3 6]]


In [32]:
## Flatten 1D
b=np.array( [[1,2,3], [4,5,6]])
print(b.flatten())  # make 1D
print ( np.squeeze(b) ) # remove single dimensionl entries
b=np.array([[[1]],[[2]]])
print(b)
print(b.flatten())  # make 1D
print ( np.squeeze(b) ) # remove single dimensionl entries

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1]]

 [[2]]]
[1 2]
[1 2]


In [33]:
# reorder
b=np.array( [[1,2,3], [4,5,6]])
print(b)
print( np.fliplr(b) )
print( np.flipud(b) )
print( np.roll(b, 1, axis=1))

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[3 1 2]
 [6 4 5]]


## Matrix Operation

In [66]:
np.linalg.norm([3,4])

5.0

In [67]:
# transpose 
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
# determinant
a = np.array([[6,1,1],[4,-2,5],[2,8,7]])
np.linalg.det(a)

-306.0

In [69]:
# inverse
np.linalg.inv(a)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [70]:
np.dot(a, np.linalg.inv(a))

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [-1.38777878e-17,  1.00000000e+00,  1.38777878e-17],
       [-4.16333634e-17,  1.38777878e-16,  1.00000000e+00]])

In [79]:
q,r = np.linalg.qr(a)
print(q)
print(r)
print(np.dot(q,r))

[[-0.80178373 -0.06178021 -0.59441237]
 [-0.53452248 -0.37068124  0.75952691]
 [-0.26726124  0.92670309  0.26418327]]
[[-7.48331477 -1.87082869 -5.34522484]
 [ 0.          8.09320703  4.57173527]
 [ 0.          0.          5.05250513]]
[[ 6.  1.  1.]
 [ 4. -2.  5.]
 [ 2.  8.  7.]]


In [82]:
s=np.linalg.solve(a, [1,2,3]) 
print(s )
print( np.dot(a, s))

[0.10130719 0.05228758 0.33986928]
[1. 2. 3.]


In [71]:
np.linalg.eig(a)

(array([11.24862343,  5.09285054, -5.34147398]),
 array([[ 0.24511338,  0.75669314,  0.02645665],
        [ 0.40622202, -0.03352363, -0.84078293],
        [ 0.88028581, -0.65291014,  0.54072554]]))

In [72]:
# identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [74]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [51]:
import scipy

In [64]:
# LU decomposition
scipy.__version__
# scipy.linalg.lu(a)  # __version__ 0.14

'1.3.1'