In [1]:
import numpy as np

In [5]:
'{0:06b}'.format(10)

'001010'

In [15]:
np.zeros((3,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [29]:
def arrtomat(n, arr):
    bitmap = np.zeros((n,n), dtype=np.int8)
    fs = '{0:0'+str(n)+'b}'
    for i,x in enumerate(arr):
        bs = fs.format(x)
#         print(bs)
        for j,bit in enumerate(bs):
            if bit=='1':
                bitmap[i][j]=1
    print(bitmap)
    return bitmap                
            

In [51]:
def mattostar(bit):
    r, c = bit.shape
    ret=[]
    for row in bit:
        line=[]
        for c in row:
            if c==1:
                line.append('#')
            else:
                line.append(' ')
        ret.append(''.join(line))
    return ret
    

In [52]:
mattostar(x)

['#####', '# # #', '### #', '#  ##', '#####']

In [53]:
def solution(n, arr1, arr2):
    answer = []
    bitmap1 = arrtomat(n, arr1)
    bitmap2 = arrtomat(n, arr2)
    bitor = np.bitwise_or(bitmap1, bitmap2)
#     print(bitor)
    answer = mattostar(bitor)
    return answer

In [54]:
x=solution(5, [9, 20, 28, 18, 11], [30, 1, 21, 17, 28])

[[0 1 0 0 1]
 [1 0 1 0 0]
 [1 1 1 0 0]
 [1 0 0 1 0]
 [0 1 0 1 1]]
[[1 1 1 1 0]
 [0 0 0 0 1]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 1 1 0 0]]


In [35]:
x

array([[1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)