In [1]:
import numpy as np


In [2]:
'''
성능 개선이 문제.
list에서 검색은 루프 탐색보다. in 키워드로 검색하는 것이 3배는 빠름.

쓸데없이 리스트에 추가하는 것 삭제. insert 횟수 감소.

위치관계에 따른 그룹을 직접 알기 위해 group matrix 추가


'''

'\n성능 개선이 문제.\nlist에서 검색은 루프 탐색보다. in 키워드로 검색하는 것이 3배는 빠름.\n\n쓸데없이 리스트에 추가하는 것 삭제. insert 횟수 감소.\n\n위치관계에 따른 그룹을 직접 알기 위해 group matrix 추가\n\n\n'

In [3]:

input = [[1, 4, 8, 10], [5, 5, 5, 5], [10, 10, 10, 10], [10, 10, 10, 20]]
height = 3
result=15

# input = [[10, 11, 10, 11], [2, 21, 20, 10], [1, 20, 21, 11], [2, 1, 2, 1]]
# height = 1
# result=18

n = len(input)
npinput = np.asarray(input)

In [3]:
# group api
groups = []

# gi=group index. -1=new
# return ; group index
def group_add(i,j, gi):
    global groups
    if gi==-1:
        groups.append([(i,j)])
        gi = len(groups)-1
        print('newgroup:',gi, 'item=', i,j)
    else:
        groups[gi].append((i,j))
        print('add group=',gi, 'item=', i,j)
    return gi

def group_find(i,j):
    if i<0 or j<0:
        return -1
    if i>=n or j>=n:
        return -1
    for gi, g in enumerate(groups):
        for f in g:
            if f[0]==i and f[1]==j:
                return gi
    return -1

# d = l, r, u, d  (left, right, up, down)
def can_move(i,j, d):
    i2,j2 = i,j
    if d=='l': j2 -=1
    if d=='r': j2 +=1
    if d=='u': i2 -=1
    if d=='d': i2 +=1
    if i2<0 or j2<0:
        return False
    if i2>=n or j2>=n:
        return False
    return abs(input[i][j] - input[i2][j2])<=height

def group_merge(gi, gj):
    global groups
    bak = groups[gj][:]
    print('group merge ',gj,'into',gi)
    groups[gi].extend(bak)
    del groups[gj]
    

In [4]:
groups.clear()
print(group_add(0,0,-1))
print(group_add(1,1,0))
print(group_add(2,2,-1))
print(group_add(3,3,1))
print(group_add(4,4,-1))
print(group_add(5,6,2))

print('find=', group_find(5,6))
print('find=', group_find(2,2))

groups

newgroup: 0 item= 0 0
0
add group= 0 item= 1 1
0
newgroup: 1 item= 2 2
1
add group= 1 item= 3 3
1
newgroup: 2 item= 4 4
2
add group= 2 item= 5 6
2
find= -1
find= 1


[[(0, 0), (1, 1)], [(2, 2), (3, 3)], [(4, 4), (5, 6)]]

In [5]:
groups

[[(0, 0), (1, 1)], [(2, 2), (3, 3)], [(4, 4), (5, 6)]]

In [6]:
group_merge(1,2)

group merge  2 into 1


In [7]:
groups

[[(0, 0), (1, 1)], [(2, 2), (3, 3), (4, 4), (5, 6)]]

In [8]:
can_move(0,2,'r')

True

In [9]:
global groups
print(input)
groups.clear()

for i in range(n):
    for j in range(n):
        gi = group_find(i,j)
        if gi==-1:
            gi = group_add(i,j, -1)
        print('check ', i,j, 'group=', gi)
            
        if can_move(i,j,'r'):
            g2 = group_find(i,j+1)
            if g2==-1:
                group_add(i,j+1,gi)
            elif g2==gi:
                pass
            else:
                group_merge(min(gi,g2), max(gi,g2))
                gi = min(gi, g2)

        if can_move(i,j,'d'):
            g2 = group_find(i+1,j)
            if g2==-1:
                group_add(i+1,j,gi)
            elif g2==gi:
                pass
            else:
                group_merge(min(gi,g2), max(gi,g2))

print(groups)


[[1, 4, 8, 10], [5, 5, 5, 5], [10, 10, 10, 10], [10, 10, 10, 20]]
newgroup: 0 item= 0 0
check  0 0 group= 0
add group= 0 item= 0 1
check  0 1 group= 0
add group= 0 item= 1 1
newgroup: 1 item= 0 2
check  0 2 group= 1
add group= 1 item= 0 3
add group= 1 item= 1 2
check  0 3 group= 1
newgroup: 2 item= 1 0
check  1 0 group= 2
group merge  2 into 0
check  1 1 group= 0
group merge  1 into 0
check  1 2 group= 0
add group= 0 item= 1 3
check  1 3 group= 0
newgroup: 1 item= 2 0
check  2 0 group= 1
add group= 1 item= 2 1
add group= 1 item= 3 0
check  2 1 group= 1
add group= 1 item= 2 2
add group= 1 item= 3 1
check  2 2 group= 1
add group= 1 item= 2 3
add group= 1 item= 3 2
check  2 3 group= 1
check  3 0 group= 1
check  3 1 group= 1
check  3 2 group= 1
newgroup: 2 item= 3 3
check  3 3 group= 2
[[(0, 0), (0, 1), (1, 1), (1, 0), (0, 2), (0, 3), (1, 2), (1, 3)], [(2, 0), (2, 1), (3, 0), (2, 2), (3, 1), (2, 3), (3, 2)], [(3, 3)]]


In [10]:
groups

[[(0, 0), (0, 1), (1, 1), (1, 0), (0, 2), (0, 3), (1, 2), (1, 3)],
 [(2, 0), (2, 1), (3, 0), (2, 2), (3, 1), (2, 3), (3, 2)],
 [(3, 3)]]

In [11]:
# 가장 짧은 곳을 연결. merge
bridge=[] # (i1,j1,i2,j2,cost)
while len(groups)>1:
    firstgroup = groups[0]
    tmpb = [] 
    mincost=99999
    mincostidx=0
    mincostgroup=0
    for it in firstgroup:
        cost=-1
        # 다른 그룹과 접하는지 검사. lrud
        # 접한다면 비용 기록. (누구랑, 누구랑 연결할 때 비용)
        gi = group_find(it[0], it[1]-1)
        if gi>0:
            cost = abs(input[it[0]][it[1]]-input[it[0]][it[1]-1])
            tmpb.append( (it[0], it[1], it[0], it[1]-1, cost) )
            if mincost>cost:
                mincost=cost
                mincostidx=len(tmpb)-1
                mincostgroup=gi
        gi = group_find(it[0], it[1]+1)
        if gi>0:
            cost = abs(input[it[0]][it[1]]-input[it[0]][it[1]+1])
            tmpb.append( (it[0], it[1], it[0], it[1]+1, cost) )           
            if mincost>cost:
                mincost=cost
                mincostidx=len(tmpb)-1
                mincostgroup=gi
        gi = group_find(it[0]-1, it[1])
        if gi>0:
            cost = abs(input[it[0]][it[1]]-input[it[0]-1][it[1]])
            tmpb.append( (it[0], it[1], it[0]-1, it[1], cost) ) 
            if mincost>cost:
                mincost=cost
                mincostidx=len(tmpb)-1
                mincostgroup=gi
        gi = group_find(it[0]+1, it[1])
        if gi>0:
            cost = abs(input[it[0]][it[1]]-input[it[0]+1][it[1]])
            tmpb.append( (it[0], it[1], it[0]+1, it[1], cost) )           
            if mincost>cost:
                mincost=cost
                mincostidx=len(tmpb)-1
                mincostgroup=gi
    print(tmpb)
    print('cost=',mincost, 'idx=',mincostidx, 'group=', mincostgroup)
    # 최소 비용 캐치. 다리 건설.
    bridge.append(tmpb[mincostidx])
    # 1그룹으로 병합
    group_merge(0, mincostgroup)

print(groups)        
print(bridge)

# total cost
total = 0
for x in bridge:
    total += x[4]
print(total)

[(1, 1, 2, 1, 5), (1, 0, 2, 0, 5), (1, 2, 2, 2, 5), (1, 3, 2, 3, 5)]
cost= 5 idx= 0 group= 1
group merge  1 into 0
[(2, 3, 3, 3, 10), (3, 2, 3, 3, 10)]
cost= 10 idx= 0 group= 1
group merge  1 into 0
[[(0, 0), (0, 1), (1, 1), (1, 0), (0, 2), (0, 3), (1, 2), (1, 3), (2, 0), (2, 1), (3, 0), (2, 2), (3, 1), (2, 3), (3, 2), (3, 3)]]
[(1, 1, 2, 1, 5), (2, 3, 3, 3, 10)]
15


In [1]:
import numpy as np


input=[]
n = 0
gheight=0
bdebug=False
# bdebug=True

groupmat = None


# d = l, r, u, d  (left, right, up, down)
def can_move(i,j, d):
    i2,j2 = i,j
    if d=='l': j2 -=1
    if d=='r': j2 +=1
    if d=='u': i2 -=1
    if d=='d': i2 +=1
    if i2<0 or j2<0:
        return False
    if i2>=n or j2>=n:
        return False
    return abs(input[i][j] - input[i2][j2])<=gheight

   
def group_find2(i,j):
    if i<0 or j<0:
        return -1
    if i>=n or j>=n:
        return -1
    return groupmat[i,j]

    
def solution(land, height):
    global input, n, gheight
    global groupmat
    
    input=land
    gheight = height
    n=len(input)

    print("N=", n)
    groupmat = np.zeros((n,n), dtype=int)
    groupcnt=0
    for i in range(n):
        if bdebug:
            print("progress ", i, "/", n)
            
        for j in range(n):
            gi = groupmat[i,j]
            if gi==0:
                groupcnt+=1
                groupmat[i,j]=groupcnt
                gi = groupcnt

            if can_move(i,j,'r'):
                g2 = groupmat[i,j+1]
                if g2==0:
                    groupmat[i,j+1]=gi
                elif g2==gi:
                    pass
                else:
                    fromg = max(gi,g2)
                    tog = min(gi,g2)
                    groupmat[groupmat==fromg] = tog
                    groupmat[groupmat>fromg] -=1
                    groupcnt-=1
                    gi = tog

            if can_move(i,j,'d'):
                g2 = groupmat[i+1,j]
                if g2==0:
                    groupmat[i+1,j]=gi
                elif g2==gi:
                    pass
                else:
                    fromg = max(gi,g2)
                    tog = min(gi,g2)
                    groupmat[groupmat==fromg] = tog
                    groupmat[groupmat>fromg] -=1
                    groupcnt-=1
                    gi = tog

    if bdebug:
        print('group count=', groupcnt)
        print('groupmat max=', np.max(groupmat))
        print(groupmat)
        
#     return 0 ; # debug phase1
    if bdebug:
        print('phase1 end.')

    # 가장 짧은 곳을 연결. merge
    bridge=[] # (i1,j1,i2,j2,cost)
    allbridge=np.empty((0,6), dtype=int)
    newfirstgroup = np.argwhere(groupmat==1).tolist()
    
    while groupcnt>1:
        mincost=99999
        mincostgroup=0
        
        if True:
            print('group count=', groupcnt)
            
        '''
       new incomming이 없을 수도 있다. 
       기존에서 다시 찾아야 함.
       1그룹에서 다른 그룹으로 연결되는 모든 다리 스캔
        '''
        ab = []
        for it in newfirstgroup:
            cost=-1
            # 다른 그룹과 접하는지 검사. lrud
            # 접한다면 비용 기록. (누구랑, 누구랑 연결할 때 비용)
            gi = group_find2(it[0], it[1]-1)
            if gi>1:
                cost = abs(input[it[0]][it[1]]-input[it[0]][it[1]-1])
                ab.append([it[0], it[1], it[0], it[1]-1, gi, cost])
            gi = group_find2(it[0], it[1]+1)
            if gi>1:
                cost = abs(input[it[0]][it[1]]-input[it[0]][it[1]+1])
                ab.append([it[0], it[1], it[0], it[1]+1, gi, cost])
            gi = group_find2(it[0]-1, it[1])
            if gi>1:
                cost = abs(input[it[0]][it[1]]-input[it[0]-1][it[1]])
                ab.append([it[0], it[1], it[0]-1, it[1], gi, cost])
            gi = group_find2(it[0]+1, it[1])
            if gi>1:
                cost = abs(input[it[0]][it[1]]-input[it[0]+1][it[1]])
                ab.append([it[0], it[1], it[0]+1, it[1], gi, cost])
                
        if len(ab)>0:
            allbridge = np.append(allbridge, np.asarray(ab), axis=0)
        if bdebug:
            print('allbridge count=', len(allbridge))
        del ab
        
        # find minimum cost
        idx = np.argmin(allbridge[:,5])
        mincost=allbridge[idx,5]
        mincostgroup = allbridge[idx,4]
        tmpb = allbridge[idx]
        
        if bdebug:
            print('min tmpb=',tmpb)
            print('mincost=',mincost, 'mincostgroup=', mincostgroup)
        
        # mincost 그룹으로 가는 계산은 이제 필요없음. 검색범위에서 제거
        idxes=np.where(allbridge[:,4]==mincostgroup)[0]
        allbridge = np.delete(allbridge, idxes, axis=0)

        # 최소 비용 캐치. 다리 건설.
        bridge.append(tmpb)
        if bdebug:
            print('bridge:', tmpb)

        # 1그룹으로 병합
        mincostindexes = np.argwhere(groupmat==mincostgroup).tolist()
        newfirstgroup = mincostindexes
        groupmat[groupmat==mincostgroup] = 1
        groupcnt -=1
        
        if bdebug:
            print('')

    if bdebug:
        print(bridge)

    # total cost
    total = 0
    for x in bridge:
        total += x[5]
    if bdebug:
        print('total=', total)
    answer = total
    return answer

In [59]:
import numpy as np

x=np.zeros((5,5), dtype=int)

In [60]:
x[x==2]=22
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [2]:
input = [[1, 4, 8, 10], [5, 5, 5, 5], [10, 10, 10, 10], [10, 10, 10, 20]]
height = 3
result=15
solution(input, height)

N= 4
group count= 3
group count= 2


15

In [5]:
for i in range(5):
    s=np.random.randint(1,100)
#      s=67
#     s=79
    print('SEED=',s)
    np.random.seed(s)
    # stress test . max 300x300
    npinput = np.random.rand(50,50)*30
    npinput = np.asarray(npinput, dtype=int)
    print(npinput)
    if solution(npinput.tolist(), 2)==-1:
        break

SEED= 29
[[25  8  2 ... 28  7 25]
 [24  4  8 ...  8  2 19]
 [29 22 22 ... 20 26 26]
 ...
 [ 5 21 15 ... 14 23 24]
 [12 13 21 ... 19 28 29]
 [26  2 21 ...  8  1 20]]
N= 50
group count= 1693
group count= 1692
group count= 1691
group count= 1690
group count= 1689
group count= 1688
group count= 1687
group count= 1686
group count= 1685
group count= 1684
group count= 1683
group count= 1682
group count= 1681
group count= 1680
group count= 1679
group count= 1678
group count= 1677
group count= 1676
group count= 1675
group count= 1674
group count= 1673
group count= 1672
group count= 1671
group count= 1670
group count= 1669
group count= 1668
group count= 1667
group count= 1666
group count= 1665
group count= 1664
group count= 1663
group count= 1662
group count= 1661
group count= 1660
group count= 1659
group count= 1658
group count= 1657
group count= 1656
group count= 1655
group count= 1654
group count= 1653
group count= 1652
group count= 1651
group count= 1650
group count= 1649
group count= 1648
g

group count= 1110
group count= 1109
group count= 1108
group count= 1107
group count= 1106
group count= 1105
group count= 1104
group count= 1103
group count= 1102
group count= 1101
group count= 1100
group count= 1099
group count= 1098
group count= 1097
group count= 1096
group count= 1095
group count= 1094
group count= 1093
group count= 1092
group count= 1091
group count= 1090
group count= 1089
group count= 1088
group count= 1087
group count= 1086
group count= 1085
group count= 1084
group count= 1083
group count= 1082
group count= 1081
group count= 1080
group count= 1079
group count= 1078
group count= 1077
group count= 1076
group count= 1075
group count= 1074
group count= 1073
group count= 1072
group count= 1071
group count= 1070
group count= 1069
group count= 1068
group count= 1067
group count= 1066
group count= 1065
group count= 1064
group count= 1063
group count= 1062
group count= 1061
group count= 1060
group count= 1059
group count= 1058
group count= 1057
group count= 1056
group coun

group count= 179
group count= 178
group count= 177
group count= 176
group count= 175
group count= 174
group count= 173
group count= 172
group count= 171
group count= 170
group count= 169
group count= 168
group count= 167
group count= 166
group count= 165
group count= 164
group count= 163
group count= 162
group count= 161
group count= 160
group count= 159
group count= 158
group count= 157
group count= 156
group count= 155
group count= 154
group count= 153
group count= 152
group count= 151
group count= 150
group count= 149
group count= 148
group count= 147
group count= 146
group count= 145
group count= 144
group count= 143
group count= 142
group count= 141
group count= 140
group count= 139
group count= 138
group count= 137
group count= 136
group count= 135
group count= 134
group count= 133
group count= 132
group count= 131
group count= 130
group count= 129
group count= 128
group count= 127
group count= 126
group count= 125
group count= 124
group count= 123
group count= 122
group count= 1

group count= 1371
group count= 1370
group count= 1369
group count= 1368
group count= 1367
group count= 1366
group count= 1365
group count= 1364
group count= 1363
group count= 1362
group count= 1361
group count= 1360
group count= 1359
group count= 1358
group count= 1357
group count= 1356
group count= 1355
group count= 1354
group count= 1353
group count= 1352
group count= 1351
group count= 1350
group count= 1349
group count= 1348
group count= 1347
group count= 1346
group count= 1345
group count= 1344
group count= 1343
group count= 1342
group count= 1341
group count= 1340
group count= 1339
group count= 1338
group count= 1337
group count= 1336
group count= 1335
group count= 1334
group count= 1333
group count= 1332
group count= 1331
group count= 1330
group count= 1329
group count= 1328
group count= 1327
group count= 1326
group count= 1325
group count= 1324
group count= 1323
group count= 1322
group count= 1321
group count= 1320
group count= 1319
group count= 1318
group count= 1317
group coun

group count= 818
group count= 817
group count= 816
group count= 815
group count= 814
group count= 813
group count= 812
group count= 811
group count= 810
group count= 809
group count= 808
group count= 807
group count= 806
group count= 805
group count= 804
group count= 803
group count= 802
group count= 801
group count= 800
group count= 799
group count= 798
group count= 797
group count= 796
group count= 795
group count= 794
group count= 793
group count= 792
group count= 791
group count= 790
group count= 789
group count= 788
group count= 787
group count= 786
group count= 785
group count= 784
group count= 783
group count= 782
group count= 781
group count= 780
group count= 779
group count= 778
group count= 777
group count= 776
group count= 775
group count= 774
group count= 773
group count= 772
group count= 771
group count= 770
group count= 769
group count= 768
group count= 767
group count= 766
group count= 765
group count= 764
group count= 763
group count= 762
group count= 761
group count= 7

group count= 1345
group count= 1344
group count= 1343
group count= 1342
group count= 1341
group count= 1340
group count= 1339
group count= 1338
group count= 1337
group count= 1336
group count= 1335
group count= 1334
group count= 1333
group count= 1332
group count= 1331
group count= 1330
group count= 1329
group count= 1328
group count= 1327
group count= 1326
group count= 1325
group count= 1324
group count= 1323
group count= 1322
group count= 1321
group count= 1320
group count= 1319
group count= 1318
group count= 1317
group count= 1316
group count= 1315
group count= 1314
group count= 1313
group count= 1312
group count= 1311
group count= 1310
group count= 1309
group count= 1308
group count= 1307
group count= 1306
group count= 1305
group count= 1304
group count= 1303
group count= 1302
group count= 1301
group count= 1300
group count= 1299
group count= 1298
group count= 1297
group count= 1296
group count= 1295
group count= 1294
group count= 1293
group count= 1292
group count= 1291
group coun

group count= 839
group count= 838
group count= 837
group count= 836
group count= 835
group count= 834
group count= 833
group count= 832
group count= 831
group count= 830
group count= 829
group count= 828
group count= 827
group count= 826
group count= 825
group count= 824
group count= 823
group count= 822
group count= 821
group count= 820
group count= 819
group count= 818
group count= 817
group count= 816
group count= 815
group count= 814
group count= 813
group count= 812
group count= 811
group count= 810
group count= 809
group count= 808
group count= 807
group count= 806
group count= 805
group count= 804
group count= 803
group count= 802
group count= 801
group count= 800
group count= 799
group count= 798
group count= 797
group count= 796
group count= 795
group count= 794
group count= 793
group count= 792
group count= 791
group count= 790
group count= 789
group count= 788
group count= 787
group count= 786
group count= 785
group count= 784
group count= 783
group count= 782
group count= 7

group count= 356
group count= 355
group count= 354
group count= 353
group count= 352
group count= 351
group count= 350
group count= 349
group count= 348
group count= 347
group count= 346
group count= 345
group count= 344
group count= 343
group count= 342
group count= 341
group count= 340
group count= 339
group count= 338
group count= 337
group count= 336
group count= 335
group count= 334
group count= 333
group count= 332
group count= 331
group count= 330
group count= 329
group count= 328
group count= 327
group count= 326
group count= 325
group count= 324
group count= 323
group count= 322
group count= 321
group count= 320
group count= 319
group count= 318
group count= 317
group count= 316
group count= 315
group count= 314
group count= 313
group count= 312
group count= 311
group count= 310
group count= 309
group count= 308
group count= 307
group count= 306
group count= 305
group count= 304
group count= 303
group count= 302
group count= 301
group count= 300
group count= 299
group count= 2

group count= 1576
group count= 1575
group count= 1574
group count= 1573
group count= 1572
group count= 1571
group count= 1570
group count= 1569
group count= 1568
group count= 1567
group count= 1566
group count= 1565
group count= 1564
group count= 1563
group count= 1562
group count= 1561
group count= 1560
group count= 1559
group count= 1558
group count= 1557
group count= 1556
group count= 1555
group count= 1554
group count= 1553
group count= 1552
group count= 1551
group count= 1550
group count= 1549
group count= 1548
group count= 1547
group count= 1546
group count= 1545
group count= 1544
group count= 1543
group count= 1542
group count= 1541
group count= 1540
group count= 1539
group count= 1538
group count= 1537
group count= 1536
group count= 1535
group count= 1534
group count= 1533
group count= 1532
group count= 1531
group count= 1530
group count= 1529
group count= 1528
group count= 1527
group count= 1526
group count= 1525
group count= 1524
group count= 1523
group count= 1522
group coun

group count= 1080
group count= 1079
group count= 1078
group count= 1077
group count= 1076
group count= 1075
group count= 1074
group count= 1073
group count= 1072
group count= 1071
group count= 1070
group count= 1069
group count= 1068
group count= 1067
group count= 1066
group count= 1065
group count= 1064
group count= 1063
group count= 1062
group count= 1061
group count= 1060
group count= 1059
group count= 1058
group count= 1057
group count= 1056
group count= 1055
group count= 1054
group count= 1053
group count= 1052
group count= 1051
group count= 1050
group count= 1049
group count= 1048
group count= 1047
group count= 1046
group count= 1045
group count= 1044
group count= 1043
group count= 1042
group count= 1041
group count= 1040
group count= 1039
group count= 1038
group count= 1037
group count= 1036
group count= 1035
group count= 1034
group count= 1033
group count= 1032
group count= 1031
group count= 1030
group count= 1029
group count= 1028
group count= 1027
group count= 1026
group coun

group count= 123
group count= 122
group count= 121
group count= 120
group count= 119
group count= 118
group count= 117
group count= 116
group count= 115
group count= 114
group count= 113
group count= 112
group count= 111
group count= 110
group count= 109
group count= 108
group count= 107
group count= 106
group count= 105
group count= 104
group count= 103
group count= 102
group count= 101
group count= 100
group count= 99
group count= 98
group count= 97
group count= 96
group count= 95
group count= 94
group count= 93
group count= 92
group count= 91
group count= 90
group count= 89
group count= 88
group count= 87
group count= 86
group count= 85
group count= 84
group count= 83
group count= 82
group count= 81
group count= 80
group count= 79
group count= 78
group count= 77
group count= 76
group count= 75
group count= 74
group count= 73
group count= 72
group count= 71
group count= 70
group count= 69
group count= 68
group count= 67
group count= 66
group count= 65
group count= 64
group count= 63


group count= 1330
group count= 1329
group count= 1328
group count= 1327
group count= 1326
group count= 1325
group count= 1324
group count= 1323
group count= 1322
group count= 1321
group count= 1320
group count= 1319
group count= 1318
group count= 1317
group count= 1316
group count= 1315
group count= 1314
group count= 1313
group count= 1312
group count= 1311
group count= 1310
group count= 1309
group count= 1308
group count= 1307
group count= 1306
group count= 1305
group count= 1304
group count= 1303
group count= 1302
group count= 1301
group count= 1300
group count= 1299
group count= 1298
group count= 1297
group count= 1296
group count= 1295
group count= 1294
group count= 1293
group count= 1292
group count= 1291
group count= 1290
group count= 1289
group count= 1288
group count= 1287
group count= 1286
group count= 1285
group count= 1284
group count= 1283
group count= 1282
group count= 1281
group count= 1280
group count= 1279
group count= 1278
group count= 1277
group count= 1276
group coun

group count= 834
group count= 833
group count= 832
group count= 831
group count= 830
group count= 829
group count= 828
group count= 827
group count= 826
group count= 825
group count= 824
group count= 823
group count= 822
group count= 821
group count= 820
group count= 819
group count= 818
group count= 817
group count= 816
group count= 815
group count= 814
group count= 813
group count= 812
group count= 811
group count= 810
group count= 809
group count= 808
group count= 807
group count= 806
group count= 805
group count= 804
group count= 803
group count= 802
group count= 801
group count= 800
group count= 799
group count= 798
group count= 797
group count= 796
group count= 795
group count= 794
group count= 793
group count= 792
group count= 791
group count= 790
group count= 789
group count= 788
group count= 787
group count= 786
group count= 785
group count= 784
group count= 783
group count= 782
group count= 781
group count= 780
group count= 779
group count= 778
group count= 777
group count= 7

In [7]:
# max 300
npinput = np.random.rand(220,220)*100
npinput = np.asarray(npinput, dtype=int)
print(npinput)
solution(npinput.tolist(), 20)
    

[[14 43 27 ... 52 12 68]
 [65 15 73 ... 87 70 77]
 [31 60 91 ... 17 68 37]
 ...
 [24 83 17 ... 48 65 83]
 [32 21 56 ... 98 29 71]
 [62  6 53 ... 89 19 15]]
N= 220
group count= 14750
group count= 14749
group count= 14748
group count= 14747
group count= 14746
group count= 14745
group count= 14744
group count= 14743
group count= 14742
group count= 14741
group count= 14740
group count= 14739
group count= 14738
group count= 14737
group count= 14736
group count= 14735
group count= 14734
group count= 14733
group count= 14732
group count= 14731
group count= 14730
group count= 14729
group count= 14728
group count= 14727
group count= 14726
group count= 14725
group count= 14724
group count= 14723
group count= 14722
group count= 14721
group count= 14720
group count= 14719
group count= 14718
group count= 14717
group count= 14716
group count= 14715
group count= 14714
group count= 14713
group count= 14712
group count= 14711
group count= 14710
group count= 14709
group count= 14708
group count= 14707
g

group count= 14127
group count= 14126
group count= 14125
group count= 14124
group count= 14123
group count= 14122
group count= 14121
group count= 14120
group count= 14119
group count= 14118
group count= 14117
group count= 14116
group count= 14115
group count= 14114
group count= 14113
group count= 14112
group count= 14111
group count= 14110
group count= 14109
group count= 14108
group count= 14107
group count= 14106
group count= 14105
group count= 14104
group count= 14103
group count= 14102
group count= 14101
group count= 14100
group count= 14099
group count= 14098
group count= 14097
group count= 14096
group count= 14095
group count= 14094
group count= 14093
group count= 14092
group count= 14091
group count= 14090
group count= 14089
group count= 14088
group count= 14087
group count= 14086
group count= 14085
group count= 14084
group count= 14083
group count= 14082
group count= 14081
group count= 14080
group count= 14079
group count= 14078
group count= 14077
group count= 14076
group count=

group count= 13579
group count= 13578
group count= 13577
group count= 13576
group count= 13575
group count= 13574
group count= 13573
group count= 13572
group count= 13571
group count= 13570
group count= 13569
group count= 13568
group count= 13567
group count= 13566
group count= 13565
group count= 13564
group count= 13563
group count= 13562
group count= 13561
group count= 13560
group count= 13559
group count= 13558
group count= 13557
group count= 13556
group count= 13555
group count= 13554
group count= 13553
group count= 13552
group count= 13551
group count= 13550
group count= 13549
group count= 13548
group count= 13547
group count= 13546
group count= 13545
group count= 13544
group count= 13543
group count= 13542
group count= 13541
group count= 13540
group count= 13539
group count= 13538
group count= 13537
group count= 13536
group count= 13535
group count= 13534
group count= 13533
group count= 13532
group count= 13531
group count= 13530
group count= 13529
group count= 13528
group count=

group count= 13072
group count= 13071
group count= 13070
group count= 13069
group count= 13068
group count= 13067
group count= 13066
group count= 13065
group count= 13064
group count= 13063
group count= 13062
group count= 13061
group count= 13060
group count= 13059
group count= 13058
group count= 13057
group count= 13056
group count= 13055
group count= 13054
group count= 13053
group count= 13052
group count= 13051
group count= 13050
group count= 13049
group count= 13048
group count= 13047
group count= 13046
group count= 13045
group count= 13044
group count= 13043
group count= 13042
group count= 13041
group count= 13040
group count= 13039
group count= 13038
group count= 13037
group count= 13036
group count= 13035
group count= 13034
group count= 13033
group count= 13032
group count= 13031
group count= 13030
group count= 13029
group count= 13028
group count= 13027
group count= 13026
group count= 13025
group count= 13024
group count= 13023
group count= 13022
group count= 13021
group count=

group count= 12568
group count= 12567
group count= 12566
group count= 12565
group count= 12564
group count= 12563
group count= 12562
group count= 12561
group count= 12560
group count= 12559
group count= 12558
group count= 12557
group count= 12556
group count= 12555
group count= 12554
group count= 12553
group count= 12552
group count= 12551
group count= 12550
group count= 12549
group count= 12548
group count= 12547
group count= 12546
group count= 12545
group count= 12544
group count= 12543
group count= 12542
group count= 12541
group count= 12540
group count= 12539
group count= 12538
group count= 12537
group count= 12536
group count= 12535
group count= 12534
group count= 12533
group count= 12532
group count= 12531
group count= 12530
group count= 12529
group count= 12528
group count= 12527
group count= 12526
group count= 12525
group count= 12524
group count= 12523
group count= 12522
group count= 12521
group count= 12520
group count= 12519
group count= 12518
group count= 12517
group count=

group count= 12096
group count= 12095
group count= 12094
group count= 12093
group count= 12092
group count= 12091
group count= 12090
group count= 12089
group count= 12088
group count= 12087
group count= 12086
group count= 12085
group count= 12084
group count= 12083
group count= 12082
group count= 12081
group count= 12080
group count= 12079
group count= 12078
group count= 12077
group count= 12076
group count= 12075
group count= 12074
group count= 12073
group count= 12072
group count= 12071
group count= 12070
group count= 12069
group count= 12068
group count= 12067
group count= 12066
group count= 12065
group count= 12064
group count= 12063
group count= 12062
group count= 12061
group count= 12060
group count= 12059
group count= 12058
group count= 12057
group count= 12056
group count= 12055
group count= 12054
group count= 12053
group count= 12052
group count= 12051
group count= 12050
group count= 12049
group count= 12048
group count= 12047
group count= 12046
group count= 12045
group count=

group count= 11622
group count= 11621
group count= 11620
group count= 11619
group count= 11618
group count= 11617
group count= 11616
group count= 11615
group count= 11614
group count= 11613
group count= 11612
group count= 11611
group count= 11610
group count= 11609
group count= 11608
group count= 11607
group count= 11606
group count= 11605
group count= 11604
group count= 11603
group count= 11602
group count= 11601
group count= 11600
group count= 11599
group count= 11598
group count= 11597
group count= 11596
group count= 11595
group count= 11594
group count= 11593
group count= 11592
group count= 11591
group count= 11590
group count= 11589
group count= 11588
group count= 11587
group count= 11586
group count= 11585
group count= 11584
group count= 11583
group count= 11582
group count= 11581
group count= 11580
group count= 11579
group count= 11578
group count= 11577
group count= 11576
group count= 11575
group count= 11574
group count= 11573
group count= 11572
group count= 11571
group count=

group count= 11172
group count= 11171
group count= 11170
group count= 11169
group count= 11168
group count= 11167
group count= 11166
group count= 11165
group count= 11164
group count= 11163
group count= 11162
group count= 11161
group count= 11160
group count= 11159
group count= 11158
group count= 11157
group count= 11156
group count= 11155
group count= 11154
group count= 11153
group count= 11152
group count= 11151
group count= 11150
group count= 11149
group count= 11148
group count= 11147
group count= 11146
group count= 11145
group count= 11144
group count= 11143
group count= 11142
group count= 11141
group count= 11140
group count= 11139
group count= 11138
group count= 11137
group count= 11136
group count= 11135
group count= 11134
group count= 11133
group count= 11132
group count= 11131
group count= 11130
group count= 11129
group count= 11128
group count= 11127
group count= 11126
group count= 11125
group count= 11124
group count= 11123
group count= 11122
group count= 11121
group count=

group count= 10740
group count= 10739
group count= 10738
group count= 10737
group count= 10736
group count= 10735
group count= 10734
group count= 10733
group count= 10732
group count= 10731
group count= 10730
group count= 10729
group count= 10728
group count= 10727
group count= 10726
group count= 10725
group count= 10724
group count= 10723
group count= 10722
group count= 10721
group count= 10720
group count= 10719
group count= 10718
group count= 10717
group count= 10716
group count= 10715
group count= 10714
group count= 10713
group count= 10712
group count= 10711
group count= 10710
group count= 10709
group count= 10708
group count= 10707
group count= 10706
group count= 10705
group count= 10704
group count= 10703
group count= 10702
group count= 10701
group count= 10700
group count= 10699
group count= 10698
group count= 10697
group count= 10696
group count= 10695
group count= 10694
group count= 10693
group count= 10692
group count= 10691
group count= 10690
group count= 10689
group count=

group count= 10106
group count= 10105
group count= 10104
group count= 10103
group count= 10102
group count= 10101
group count= 10100
group count= 10099
group count= 10098
group count= 10097
group count= 10096
group count= 10095
group count= 10094
group count= 10093
group count= 10092
group count= 10091
group count= 10090
group count= 10089
group count= 10088
group count= 10087
group count= 10086
group count= 10085
group count= 10084
group count= 10083
group count= 10082
group count= 10081
group count= 10080
group count= 10079
group count= 10078
group count= 10077
group count= 10076
group count= 10075
group count= 10074
group count= 10073
group count= 10072
group count= 10071
group count= 10070
group count= 10069
group count= 10068
group count= 10067
group count= 10066
group count= 10065
group count= 10064
group count= 10063
group count= 10062
group count= 10061
group count= 10060
group count= 10059
group count= 10058
group count= 10057
group count= 10056
group count= 10055
group count=

group count= 9495
group count= 9494
group count= 9493
group count= 9492
group count= 9491
group count= 9490
group count= 9489
group count= 9488
group count= 9487
group count= 9486
group count= 9485
group count= 9484
group count= 9483
group count= 9482
group count= 9481
group count= 9480
group count= 9479
group count= 9478
group count= 9477
group count= 9476
group count= 9475
group count= 9474
group count= 9473
group count= 9472
group count= 9471
group count= 9470
group count= 9469
group count= 9468
group count= 9467
group count= 9466
group count= 9465
group count= 9464
group count= 9463
group count= 9462
group count= 9461
group count= 9460
group count= 9459
group count= 9458
group count= 9457
group count= 9456
group count= 9455
group count= 9454
group count= 9453
group count= 9452
group count= 9451
group count= 9450
group count= 9449
group count= 9448
group count= 9447
group count= 9446
group count= 9445
group count= 9444
group count= 9443
group count= 9442
group count= 9441
group coun

group count= 8905
group count= 8904
group count= 8903
group count= 8902
group count= 8901
group count= 8900
group count= 8899
group count= 8898
group count= 8897
group count= 8896
group count= 8895
group count= 8894
group count= 8893
group count= 8892
group count= 8891
group count= 8890
group count= 8889
group count= 8888
group count= 8887
group count= 8886
group count= 8885
group count= 8884
group count= 8883
group count= 8882
group count= 8881
group count= 8880
group count= 8879
group count= 8878
group count= 8877
group count= 8876
group count= 8875
group count= 8874
group count= 8873
group count= 8872
group count= 8871
group count= 8870
group count= 8869
group count= 8868
group count= 8867
group count= 8866
group count= 8865
group count= 8864
group count= 8863
group count= 8862
group count= 8861
group count= 8860
group count= 8859
group count= 8858
group count= 8857
group count= 8856
group count= 8855
group count= 8854
group count= 8853
group count= 8852
group count= 8851
group coun

group count= 8327
group count= 8326
group count= 8325
group count= 8324
group count= 8323
group count= 8322
group count= 8321
group count= 8320
group count= 8319
group count= 8318
group count= 8317
group count= 8316
group count= 8315
group count= 8314
group count= 8313
group count= 8312
group count= 8311
group count= 8310
group count= 8309
group count= 8308
group count= 8307
group count= 8306
group count= 8305
group count= 8304
group count= 8303
group count= 8302
group count= 8301
group count= 8300
group count= 8299
group count= 8298
group count= 8297
group count= 8296
group count= 8295
group count= 8294
group count= 8293
group count= 8292
group count= 8291
group count= 8290
group count= 8289
group count= 8288
group count= 8287
group count= 8286
group count= 8285
group count= 8284
group count= 8283
group count= 8282
group count= 8281
group count= 8280
group count= 8279
group count= 8278
group count= 8277
group count= 8276
group count= 8275
group count= 8274
group count= 8273
group coun

group count= 7748
group count= 7747
group count= 7746
group count= 7745
group count= 7744
group count= 7743
group count= 7742
group count= 7741
group count= 7740
group count= 7739
group count= 7738
group count= 7737
group count= 7736
group count= 7735
group count= 7734
group count= 7733
group count= 7732
group count= 7731
group count= 7730
group count= 7729
group count= 7728
group count= 7727
group count= 7726
group count= 7725
group count= 7724
group count= 7723
group count= 7722
group count= 7721
group count= 7720
group count= 7719
group count= 7718
group count= 7717
group count= 7716
group count= 7715
group count= 7714
group count= 7713
group count= 7712
group count= 7711
group count= 7710
group count= 7709
group count= 7708
group count= 7707
group count= 7706
group count= 7705
group count= 7704
group count= 7703
group count= 7702
group count= 7701
group count= 7700
group count= 7699
group count= 7698
group count= 7697
group count= 7696
group count= 7695
group count= 7694
group coun

group count= 7156
group count= 7155
group count= 7154
group count= 7153
group count= 7152
group count= 7151
group count= 7150
group count= 7149
group count= 7148
group count= 7147
group count= 7146
group count= 7145
group count= 7144
group count= 7143
group count= 7142
group count= 7141
group count= 7140
group count= 7139
group count= 7138
group count= 7137
group count= 7136
group count= 7135
group count= 7134
group count= 7133
group count= 7132
group count= 7131
group count= 7130
group count= 7129
group count= 7128
group count= 7127
group count= 7126
group count= 7125
group count= 7124
group count= 7123
group count= 7122
group count= 7121
group count= 7120
group count= 7119
group count= 7118
group count= 7117
group count= 7116
group count= 7115
group count= 7114
group count= 7113
group count= 7112
group count= 7111
group count= 7110
group count= 7109
group count= 7108
group count= 7107
group count= 7106
group count= 7105
group count= 7104
group count= 7103
group count= 7102
group coun

group count= 6606
group count= 6605
group count= 6604
group count= 6603
group count= 6602
group count= 6601
group count= 6600
group count= 6599
group count= 6598
group count= 6597
group count= 6596
group count= 6595
group count= 6594
group count= 6593
group count= 6592
group count= 6591
group count= 6590
group count= 6589
group count= 6588
group count= 6587
group count= 6586
group count= 6585
group count= 6584
group count= 6583
group count= 6582
group count= 6581
group count= 6580
group count= 6579
group count= 6578
group count= 6577
group count= 6576
group count= 6575
group count= 6574
group count= 6573
group count= 6572
group count= 6571
group count= 6570
group count= 6569
group count= 6568
group count= 6567
group count= 6566
group count= 6565
group count= 6564
group count= 6563
group count= 6562
group count= 6561
group count= 6560
group count= 6559
group count= 6558
group count= 6557
group count= 6556
group count= 6555
group count= 6554
group count= 6553
group count= 6552
group coun

group count= 6020
group count= 6019
group count= 6018
group count= 6017
group count= 6016
group count= 6015
group count= 6014
group count= 6013
group count= 6012
group count= 6011
group count= 6010
group count= 6009
group count= 6008
group count= 6007
group count= 6006
group count= 6005
group count= 6004
group count= 6003
group count= 6002
group count= 6001
group count= 6000
group count= 5999
group count= 5998
group count= 5997
group count= 5996
group count= 5995
group count= 5994
group count= 5993
group count= 5992
group count= 5991
group count= 5990
group count= 5989
group count= 5988
group count= 5987
group count= 5986
group count= 5985
group count= 5984
group count= 5983
group count= 5982
group count= 5981
group count= 5980
group count= 5979
group count= 5978
group count= 5977
group count= 5976
group count= 5975
group count= 5974
group count= 5973
group count= 5972
group count= 5971
group count= 5970
group count= 5969
group count= 5968
group count= 5967
group count= 5966
group coun

group count= 5503
group count= 5502
group count= 5501
group count= 5500
group count= 5499
group count= 5498
group count= 5497
group count= 5496
group count= 5495
group count= 5494
group count= 5493
group count= 5492
group count= 5491
group count= 5490
group count= 5489
group count= 5488
group count= 5487
group count= 5486
group count= 5485
group count= 5484
group count= 5483
group count= 5482
group count= 5481
group count= 5480
group count= 5479
group count= 5478
group count= 5477
group count= 5476
group count= 5475
group count= 5474
group count= 5473
group count= 5472
group count= 5471
group count= 5470
group count= 5469
group count= 5468
group count= 5467
group count= 5466
group count= 5465
group count= 5464
group count= 5463
group count= 5462
group count= 5461
group count= 5460
group count= 5459
group count= 5458
group count= 5457
group count= 5456
group count= 5455
group count= 5454
group count= 5453
group count= 5452
group count= 5451
group count= 5450
group count= 5449
group coun

group count= 4902
group count= 4901
group count= 4900
group count= 4899
group count= 4898
group count= 4897
group count= 4896
group count= 4895
group count= 4894
group count= 4893
group count= 4892
group count= 4891
group count= 4890
group count= 4889
group count= 4888
group count= 4887
group count= 4886
group count= 4885
group count= 4884
group count= 4883
group count= 4882
group count= 4881
group count= 4880
group count= 4879
group count= 4878
group count= 4877
group count= 4876
group count= 4875
group count= 4874
group count= 4873
group count= 4872
group count= 4871
group count= 4870
group count= 4869
group count= 4868
group count= 4867
group count= 4866
group count= 4865
group count= 4864
group count= 4863
group count= 4862
group count= 4861
group count= 4860
group count= 4859
group count= 4858
group count= 4857
group count= 4856
group count= 4855
group count= 4854
group count= 4853
group count= 4852
group count= 4851
group count= 4850
group count= 4849
group count= 4848
group coun

group count= 4326
group count= 4325
group count= 4324
group count= 4323
group count= 4322
group count= 4321
group count= 4320
group count= 4319
group count= 4318
group count= 4317
group count= 4316
group count= 4315
group count= 4314
group count= 4313
group count= 4312
group count= 4311
group count= 4310
group count= 4309
group count= 4308
group count= 4307
group count= 4306
group count= 4305
group count= 4304
group count= 4303
group count= 4302
group count= 4301
group count= 4300
group count= 4299
group count= 4298
group count= 4297
group count= 4296
group count= 4295
group count= 4294
group count= 4293
group count= 4292
group count= 4291
group count= 4290
group count= 4289
group count= 4288
group count= 4287
group count= 4286
group count= 4285
group count= 4284
group count= 4283
group count= 4282
group count= 4281
group count= 4280
group count= 4279
group count= 4278
group count= 4277
group count= 4276
group count= 4275
group count= 4274
group count= 4273
group count= 4272
group coun

group count= 3728
group count= 3727
group count= 3726
group count= 3725
group count= 3724
group count= 3723
group count= 3722
group count= 3721
group count= 3720
group count= 3719
group count= 3718
group count= 3717
group count= 3716
group count= 3715
group count= 3714
group count= 3713
group count= 3712
group count= 3711
group count= 3710
group count= 3709
group count= 3708
group count= 3707
group count= 3706
group count= 3705
group count= 3704
group count= 3703
group count= 3702
group count= 3701
group count= 3700
group count= 3699
group count= 3698
group count= 3697
group count= 3696
group count= 3695
group count= 3694
group count= 3693
group count= 3692
group count= 3691
group count= 3690
group count= 3689
group count= 3688
group count= 3687
group count= 3686
group count= 3685
group count= 3684
group count= 3683
group count= 3682
group count= 3681
group count= 3680
group count= 3679
group count= 3678
group count= 3677
group count= 3676
group count= 3675
group count= 3674
group coun

group count= 3051
group count= 3050
group count= 3049
group count= 3048
group count= 3047
group count= 3046
group count= 3045
group count= 3044
group count= 3043
group count= 3042
group count= 3041
group count= 3040
group count= 3039
group count= 3038
group count= 3037
group count= 3036
group count= 3035
group count= 3034
group count= 3033
group count= 3032
group count= 3031
group count= 3030
group count= 3029
group count= 3028
group count= 3027
group count= 3026
group count= 3025
group count= 3024
group count= 3023
group count= 3022
group count= 3021
group count= 3020
group count= 3019
group count= 3018
group count= 3017
group count= 3016
group count= 3015
group count= 3014
group count= 3013
group count= 3012
group count= 3011
group count= 3010
group count= 3009
group count= 3008
group count= 3007
group count= 3006
group count= 3005
group count= 3004
group count= 3003
group count= 3002
group count= 3001
group count= 3000
group count= 2999
group count= 2998
group count= 2997
group coun

group count= 2383
group count= 2382
group count= 2381
group count= 2380
group count= 2379
group count= 2378
group count= 2377
group count= 2376
group count= 2375
group count= 2374
group count= 2373
group count= 2372
group count= 2371
group count= 2370
group count= 2369
group count= 2368
group count= 2367
group count= 2366
group count= 2365
group count= 2364
group count= 2363
group count= 2362
group count= 2361
group count= 2360
group count= 2359
group count= 2358
group count= 2357
group count= 2356
group count= 2355
group count= 2354
group count= 2353
group count= 2352
group count= 2351
group count= 2350
group count= 2349
group count= 2348
group count= 2347
group count= 2346
group count= 2345
group count= 2344
group count= 2343
group count= 2342
group count= 2341
group count= 2340
group count= 2339
group count= 2338
group count= 2337
group count= 2336
group count= 2335
group count= 2334
group count= 2333
group count= 2332
group count= 2331
group count= 2330
group count= 2329
group coun

group count= 1867
group count= 1866
group count= 1865
group count= 1864
group count= 1863
group count= 1862
group count= 1861
group count= 1860
group count= 1859
group count= 1858
group count= 1857
group count= 1856
group count= 1855
group count= 1854
group count= 1853
group count= 1852
group count= 1851
group count= 1850
group count= 1849
group count= 1848
group count= 1847
group count= 1846
group count= 1845
group count= 1844
group count= 1843
group count= 1842
group count= 1841
group count= 1840
group count= 1839
group count= 1838
group count= 1837
group count= 1836
group count= 1835
group count= 1834
group count= 1833
group count= 1832
group count= 1831
group count= 1830
group count= 1829
group count= 1828
group count= 1827
group count= 1826
group count= 1825
group count= 1824
group count= 1823
group count= 1822
group count= 1821
group count= 1820
group count= 1819
group count= 1818
group count= 1817
group count= 1816
group count= 1815
group count= 1814
group count= 1813
group coun

group count= 1332
group count= 1331
group count= 1330
group count= 1329
group count= 1328
group count= 1327
group count= 1326
group count= 1325
group count= 1324
group count= 1323
group count= 1322
group count= 1321
group count= 1320
group count= 1319
group count= 1318
group count= 1317
group count= 1316
group count= 1315
group count= 1314
group count= 1313
group count= 1312
group count= 1311
group count= 1310
group count= 1309
group count= 1308
group count= 1307
group count= 1306
group count= 1305
group count= 1304
group count= 1303
group count= 1302
group count= 1301
group count= 1300
group count= 1299
group count= 1298
group count= 1297
group count= 1296
group count= 1295
group count= 1294
group count= 1293
group count= 1292
group count= 1291
group count= 1290
group count= 1289
group count= 1288
group count= 1287
group count= 1286
group count= 1285
group count= 1284
group count= 1283
group count= 1282
group count= 1281
group count= 1280
group count= 1279
group count= 1278
group coun

group count= 816
group count= 815
group count= 814
group count= 813
group count= 812
group count= 811
group count= 810
group count= 809
group count= 808
group count= 807
group count= 806
group count= 805
group count= 804
group count= 803
group count= 802
group count= 801
group count= 800
group count= 799
group count= 798
group count= 797
group count= 796
group count= 795
group count= 794
group count= 793
group count= 792
group count= 791
group count= 790
group count= 789
group count= 788
group count= 787
group count= 786
group count= 785
group count= 784
group count= 783
group count= 782
group count= 781
group count= 780
group count= 779
group count= 778
group count= 777
group count= 776
group count= 775
group count= 774
group count= 773
group count= 772
group count= 771
group count= 770
group count= 769
group count= 768
group count= 767
group count= 766
group count= 765
group count= 764
group count= 763
group count= 762
group count= 761
group count= 760
group count= 759
group count= 7

group count= 182
group count= 181
group count= 180
group count= 179
group count= 178
group count= 177
group count= 176
group count= 175
group count= 174
group count= 173
group count= 172
group count= 171
group count= 170
group count= 169
group count= 168
group count= 167
group count= 166
group count= 165
group count= 164
group count= 163
group count= 162
group count= 161
group count= 160
group count= 159
group count= 158
group count= 157
group count= 156
group count= 155
group count= 154
group count= 153
group count= 152
group count= 151
group count= 150
group count= 149
group count= 148
group count= 147
group count= 146
group count= 145
group count= 144
group count= 143
group count= 142
group count= 141
group count= 140
group count= 139
group count= 138
group count= 137
group count= 136
group count= 135
group count= 134
group count= 133
group count= 132
group count= 131
group count= 130
group count= 129
group count= 128
group count= 127
group count= 126
group count= 125
group count= 1

444962

In [387]:
np.abs(npinput[0]-npinput[0][0])

array([ 0,  7, 11,  7, 12, 78, 33, 11, 55, 17, 67,  1, 43, 23, 59, 19, 48,
       65, 70, 42,  6,  7, 54, 86, 18, 22, 46, 86, 29, 64,  1,  7, 13,  2,
       30, 21, 81,  6,  8,  9, 39, 14, 19, 20, 81, 26, 53,  7, 86,  6, 65,
       32, 37, 21, 10,  2, 59, 39, 15, 62, 21,  5, 17, 23,  3, 39, 67, 37,
       86, 12, 51, 84, 58, 15, 25,  7, 63,  8, 33, 48, 24, 24, 22, 26, 17,
       11, 58, 40,  2, 60, 51, 34, 37, 73,  4, 38,  5, 62, 41,  6, 34, 20,
       42,  7, 33, 67,  5, 25, 73, 47, 75, 59, 75, 81,  1, 25, 12, 12,  4,
        7, 47, 12, 62, 70, 85,  9, 10, 11, 35, 74,  1, 27, 19, 20, 70, 57,
        0, 63, 75, 18,  1, 27, 63, 12, 68, 21, 57, 37, 79, 43, 67, 86, 35,
       14, 71, 51, 86, 84, 85, 79,  3, 77,  3, 31, 78,  9, 80, 69, 32,  9,
       43, 28, 64, 44, 64, 51, 39, 27, 50, 58, 58, 26, 45, 55, 65, 49, 78,
       53, 67, 26, 76, 74, 78, 71, 66, 54, 20, 78, 37,  0, 46, 69, 35, 78,
       14, 24, 54, 31,  3, 81, 83, 58, 24,  6, 30, 23, 34, 36,  9, 41, 74,
       62, 64, 43,  4, 21

In [328]:
np.max(npinput)

99

In [329]:
npinput==23

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False]])

In [108]:
x2=np.argwhere(npinput==23)[0:5]
print(x2)

[[ 0 13]
 [ 0 72]
 [ 0 85]
 [ 1 34]
 [ 1 85]]


In [109]:
for xi in x2:
    print(xi)

[ 0 13]
[ 0 72]
[ 0 85]
[ 1 34]
[ 1 85]


In [122]:
len(x2)

5

In [37]:
all_bridge=[ [1,1,2,1,1,10],[2,1,2,1,2,10], [3,1,2,1,1,10], [4,1,2,1,1,10],[5,1,2,1,2,10], [6,1,2,1,1,10]]
print(all_bridge)

[[1, 1, 2, 1, 1, 10], [2, 1, 2, 1, 2, 10], [3, 1, 2, 1, 1, 10], [4, 1, 2, 1, 1, 10], [5, 1, 2, 1, 2, 10], [6, 1, 2, 1, 1, 10]]


In [38]:
tmpb=[3,1,2,1,1,10]

In [39]:
# mincost 그룹 다리를 삭제. except tmpb
for x in all_bridge:
    if x[4]==1:
        if x==tmpb:
            pass
        else:
            all_bridge.remove(x)
print(all_bridge)

[[2, 1, 2, 1, 2, 10], [3, 1, 2, 1, 1, 10], [5, 1, 2, 1, 2, 10]]


In [40]:
npa = np.asarray(all_bridge)
print(npa)

[[ 2  1  2  1  2 10]
 [ 3  1  2  1  1 10]
 [ 5  1  2  1  2 10]]


In [41]:
np.argmin(npa[:,5])

0

In [42]:
np.delete(npa, [3,5], axis=0)

C:\DevTools\py37\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  """Entry point for launching an IPython kernel.


array([[ 2,  1,  2,  1,  2, 10],
       [ 3,  1,  2,  1,  1, 10],
       [ 5,  1,  2,  1,  2, 10]])

In [43]:
npa

array([[ 2,  1,  2,  1,  2, 10],
       [ 3,  1,  2,  1,  1, 10],
       [ 5,  1,  2,  1,  2, 10]])

In [44]:
np.append(npa,[[8,8,9,9,1,2]], axis=0)

array([[ 2,  1,  2,  1,  2, 10],
       [ 3,  1,  2,  1,  1, 10],
       [ 5,  1,  2,  1,  2, 10],
       [ 8,  8,  9,  9,  1,  2]])

In [47]:
npa[:,4]

array([2, 1, 2])

In [51]:
np.where(npa[:,4]==2)

(array([0, 2], dtype=int64),)

In [362]:
a=np.empty((0,6), dtype=int)

In [365]:
a=np.append(a, [[1,2,3,4,5,6]], axis=0)

In [366]:
a

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [367]:
len(a)

2