In [21]:
import numpy as np
import copy

In [9]:
s='fdsifjdEAFSfsdifjdszvkv'
sorts=sorted(s, reverse=True)
print(''.join(sorts))


zvvssskjjiiffffddddSFEA


In [5]:
t=list(s)
print(t)

['f', 'd', 's', 'i', 'f', 'j', 'd', 'E', 'A', 'F', 'S', 'f', 's', 'd', 'i', 'f', 'j', 'd', 's', 'z', 'v', 'k', 'v']


In [12]:
list(range(3,11,2))

[3, 5, 7, 9]

In [18]:
def solution(n):
    answer = 0
    di={1}
    for i in range(1, n//2+1):
        if n%i==0:
            di.add(i)
            di.add(n/i)
    print(di)
    answer = sum(di)
    return answer

solution(5)

{1, 5.0}


6.0

In [2]:
a=[1,2,3,4]

In [3]:
print(list(reversed(a)))

[4, 3, 2, 1]


In [4]:
a

[1, 2, 3, 4]

In [5]:
a.reverse()

In [6]:
a

[4, 3, 2, 1]

In [7]:
npdata = np.asarray(np.random.rand(1000)*1000000, dtype=int)

In [8]:
listdata = npdata.tolist()
listdata[-1]

862279

In [9]:
%time (228157 in listdata)

Wall time: 0 ns


False

In [10]:
import itertools

In [19]:
pool = 'ABCDE'
x=itertools.combinations(pool, 3)

In [20]:
print(x)

In [21]:
for xi in x:
    print (xi)

('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'E')
('B', 'C', 'D')
('B', 'C', 'E')
('B', 'D', 'E')
('C', 'D', 'E')


In [19]:
2**10

1024

In [22]:
n1 = np.asarray([[1,2],[3,4]])
n2 = np.asarray([[5,6],[7,8]]) 
n3 = n1+n2

In [23]:
print(n3)

[[ 6  8]
 [10 12]]


In [25]:
n3.tolist()

[[6, 8], [10, 12]]

In [29]:
list(np.linspace(1,10,5))

[1.0, 3.25, 5.5, 7.75, 10.0]

In [31]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [72]:
import numpy as np

def solution(N, stages):
    answer = []
    failrate = []
    stages = np.asarray(stages)
    for i in range(1,N+1):
        failcnt = np.sum( stages==i )
        users = np.sum( stages>=i )
        epsilon = 0.0000000001*i
        # print(failcnt, users)
        if users==0:
            failrate.append(0-epsilon)
        else:
            failrate.append(failcnt/users-epsilon)
        
    failrate = np.asarray(failrate)
    print(failrate)
    answer = (-failrate).argsort() # 내림차순
    answer = answer+1
    answer = answer.tolist()
    print(answer)
    return answer



In [73]:
solution(5, [2, 1, 2, 6, 2, 4, 3, 3])

[ 1.25000000e-01  4.28571428e-01  5.00000000e-01  5.00000000e-01
 -5.00000000e-10]
[3, 4, 2, 1, 5]


[3, 4, 2, 1, 5]

In [59]:
x=np.array([4,6,8,1,2,4])

In [60]:
x.argsort()

array([3, 4, 0, 5, 1, 2], dtype=int64)

In [61]:
(-x).argsort()

array([2, 1, 0, 5, 4, 3], dtype=int64)

In [74]:
from scipy.stats import rankdata